name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    environment: "Peatreat's Server"
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v3
        
    - name: ðŸš€ Run
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVERHOST }}
        username: ${{ secrets.SERVERUSERNAME }}
        password: ${{ secrets.SERVERPASSWORD }}
        port: 22
        source: ./
        target: ~/VoiceGroove
        script: |
          cd ~/VoiceGroove && npm run pm2
